title: Joe's lifting PBs
description:  Tracking my weightlifting!
url: https://jmdkc.github.io
baseurl: ''
theme_skin: blue

sass:
  sass_dir: _sass
  style: compressed

plugins:
    - jekyll-minifier

exclude:
  - docker-compose.yml
